
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 18 16:38:31 BRST 2017
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RSRVDA_DO = 11;
  public static final int COMENTARIO_BLOCO_SEM_ABRIR = 42;
  public static final int ATRIBUIÇÃO = 21;
  public static final int RSRVDA_INTEGER = 14;
  public static final int RSRVDA_ELSE = 9;
  public static final int RSRVDA_END = 6;
  public static final int OP_NOT = 34;
  public static final int OP_AND = 33;
  public static final int RSRVDA_THEN = 8;
  public static final int DOIS_PONTOS = 17;
  public static final int COMENTARIO_LINHA = 39;
  public static final int PONTO = 38;
  public static final int VIRGULA = 18;
  public static final int RSRVDA_VAR = 3;
  public static final int OP_DIV = 30;
  public static final int ABRE_P = 19;
  public static final int IDENTIFICADOR = 37;
  public static final int RSRVDA_WHILE = 10;
  public static final int RSRVDA_PROCEDURE = 4;
  public static final int OP_DIFERENTE = 26;
  public static final int RSRVDA_BOOLEAN = 15;
  public static final int EOF = 0;
  public static final int RSRVDA_PROGRAM = 2;
  public static final int COMENTARIO_BLOCO_SEM_FECHAR = 41;
  public static final int RSRVDA_FALSE = 13;
  public static final int error = 1;
  public static final int RSRVDA_IF = 7;
  public static final int OP_MULT = 31;
  public static final int OP_OR = 32;
  public static final int OP_SOMA = 28;
  public static final int COMENTARIO_BLOCO = 40;
  public static final int FECHA_P = 20;
  public static final int NUM_INTEIRO = 35;
  public static final int NUM_REAL = 36;
  public static final int OP_IGUAL = 27;
  public static final int PTO_VIRGULA = 16;
  public static final int OP_MENOR_IGUAL = 24;
  public static final int OP_MAIOR_IGUAL = 25;
  public static final int OP_SUB = 29;
  public static final int CHAR_INVALIDO = 44;
  public static final int NUM_REAL_MALFORMADO = 43;
  public static final int OP_MAIOR = 23;
  public static final int RSRVDA_TRUE = 12;
  public static final int OP_MENOR = 22;
  public static final int RSRVDA_BEGIN = 5;
}

